[pytest]
addopts = --browser-channel=chrome
          -n 10
          --dist=loadfile
          --output=artifacts
          --video=retain-on-failure
          --screenshot=on
          --tracing=retain-on-failure
          --alluredir=allure-results